version: "3.9"

services:
  app:
    image: node:20
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  

networks:
  default:
    name: yellaw-cms_default